export const traductions = {
    fr: {
        common: {
            loading: "Chargement...",
            send: "Envoyer",
            sending: "Envoi en cours...",
            sent: "Envoyé !",
            back: "Retour",
            error: "Erreur",
            email: "Email",
            password: "Mot de passe",
            submit: "Valider",
            cancel: "Annuler",
            save: "Enregistrer",
            delete: "Supprimer",
            edit: "Modifier",
            search: "Rechercher...",
            actions: "Actions",
            status: "Statut",
            active: "Actif",
            blocked: "Bloqué",
            suspended: "Suspendu",
            id: "ID",
            date: "Date",
            amount: "Montant",
            description: "Description",
            type: "Type"
        },
        navbar: {
            home: "Accueil",
            services: "Services",
            about: "À propos",
            contact: "Contact",
            clientSpace: "Espace Client",
            login: "Connexion",
            logout: "Déconnexion",
            security: "Sécurité & Mot de passe",
            subtitle: "Yado_Bank",
            theme: "Thème",
            dashboard: "Tableau de Bord",
            menu: "Menu"
        },
        sidebar: {
            admin: "Administration",
            dashboard: "Tableau de Bord",
            agentSpace: "Espace Agent",
            managementConsole: "Console de Gestion",
            newClient: "Nouveau Client",
            myAccount: "Mon Compte",
            myDashboard: "Mon Tableau de Bord",
            makeTransfer: "Faire un virement",
            becomeClient: "Je deviens client",
            howItWorks: "Comment ça marche",
            faq: "Foire aux questions",
            contactUs: "Nous contacter",
            needHelp: "Besoin d'aide ?",
            advisors: "Nos conseillers sont là pour vous."
        },
        home: {
            heroTitle: "Votre banque,",
            heroTitleAccent: "votre avenir.",
            heroDesc: "Des solutions bancaires innovantes et sécurisées pour accompagner tous vos projets de vie. L'excellence bancaire au service de votre réussite.",
            accessAccount: "Accéder à mon compte",
            discoverOffers: "Découvrir nos offres",
            servicesTitle: "Nos Services d'Excellence",
            s1Title: "Sécurité Maximale",
            s1Desc: "Vos données et transactions sont protégées par les protocoles de cryptage les plus avancés.",
            s2Title: "Banque en Ligne 24/7",
            s2Desc: "Accédez à vos comptes, effectuez des virements et gérez votre épargne où que vous soyez.",
            s3Title: "Cartes Premium",
            s3Desc: "Des cartes bancaires adaptées à votre style de vie avec des plafonds et assurances exclusifs.",
            readyTitle: "Prêt à nous rejoindre ?",
            readyDesc: "Ouvrez un compte en quelques minutes et profitez de services bancaires repensés pour vous.",
            contactAdvisor: "Contacter un conseiller"
        },
        services: {
            title: "Une gamme complète de services",
            subtitle: "NOS SOLUTIONS",
            intro: "Découvrez nos solutions bancaires conçues pour répondre à l'ensemble de vos besoins quotidiens et projets d'avenir.",
            cards: {
                secure: { title: "Comptes Sécurisés", desc: "Des comptes courants et épargne avec une sécurité de niveau militaire." },
                intl: { title: "Virements Internationaux", desc: "Envoyez de l'argent partout dans le monde avec des taux compétitifs." },
                cards: { title: "Cartes Premium", desc: "Une large gamme de cartes bancaires (Gold, Platinum, Infinite)." },
                wealth: { title: "Gestion de Patrimoine", desc: "Des experts dédiés pour optimizar vos investissements." },
                mobile: { title: "Banque Mobile", desc: "Gérez vos comptes du bout des doigts avec notre app." },
                support: { title: "Service Client Dédié", desc: "Une équipe d'experts à votre écoute 7j/7." }
            }
        },
        about: {
            title: "L'excellence depuis 2026",
            subtitle: "NOTRE HISTOIRE",
            whoTitle: "Qui sommes-nous ?",
            whoDesc1: "Yado_Bank est née de la vision de deux experts, Yasser Habri et Doha Allali, souhaitant redéfinir l'expérience bancaire au Maroc.",
            whoDesc2: "Notre mission est simple : offrir à chaque client un accompagnement sur-mesure.",
            excellenceTitle: "Excellence & Innovation",
            excellenceDesc: "Nous investissons continuellement dans les dernières technologies.",
            proximityTitle: "Proximité Client",
            proximityDesc: "Plus qu'une banque, nous sommes un partenaire de confiance."
        },
        contact: {
            title: "Contactez-nous",
            subtitle: "UNE QUESTION ?",
            coordsTitle: "Nos Coordonnées",
            formTitle: "Envoyez-nous un message",
            name: "Nom",
            firstname: "Prénom",
            message: "Message",
            placeholderMsg: "Comment pouvons-nous vous aider ?",
            btnSend: "Envoyer le message"
        },
        login: {
            title: "Espace Client",
            agentTitle: "Espace Collaborateur",
            subtitle: "Connectez-vous à votre banque en ligne",
            agentSubtitle: "Accès réservé au personnel Yado_Bank",
            usernamePlaceholder: "Nom d'utilisateur",
            agentPlaceholder: "Matricule",
            passwordPlaceholder: "••••••••••••",
            forgotPassword: "Mot de passe oublié ?",
            loginBtn: "Se connecter",
            footer: "© 2026 Yasser Habri & Doha Allali Bank. Tous droits réservés.",
            tabClient: "Client",
            tabAgent: "Staff (Admin)"
        },
        admin: {
            title: "Centre de Contrôle",
            subtitle: "Gestion globale et supervision de l'architecture bancaire.",
            badge: "Super Admin",
            activeAgents: "Agents Actifs",
            volume: "Volume Global",
            health: "Santé Système",
            staffList: "Personnel",
            addAgent: "Ajouter un Agent",
            noAgents: "Aucun agent trouvé."
        },
        agent: {
            title: "Console de Gestion",
            subtitle: "Administration centralisée des clients et comptes bancaires.",
            badge: "Espace Agent",
            newClient: "Nouveau Client",
            newAccount: "Nouveau Compte",
            clientsTab: "Clients",
            accountsTab: "Comptes",
            searchClient: "Rechercher un client (Nom, CIN)...",
            searchAccount: "Rechercher un compte (RIB)...",
            noClients: "Aucun client trouvé.",
            noAccounts: "Aucun compte trouvé.",
            balance: "Solde",
            type: "Type"
        },
        client: {
            title: "Mes Comptes",
            subtitle: "Vue d'ensemble de votre patrimoine.",
            badge: "Espace Client",
            newTransfer: "Nouveau Virement",
            balance: "Solde Actuel",
            history: "Historique des Opérations",
            noOps: "Aucune opération trouvée.",
            credit: "CRÉDIT",
            debit: "DÉBIT"
        }
    },
    en: {
        common: {
            loading: "Loading...",
            send: "Send",
            sending: "Sending...",
            sent: "Sent!",
            back: "Back",
            error: "Error",
            email: "Email",
            password: "Password",
            submit: "Submit",
            cancel: "Cancel",
            save: "Save",
            delete: "Delete",
            edit: "Edit",
            search: "Search...",
            actions: "Actions",
            status: "Status",
            active: "Active",
            blocked: "Blocked",
            suspended: "Suspended",
            id: "ID",
            date: "Date",
            amount: "Amount",
            description: "Description",
            type: "Type"
        },
        navbar: {
            home: "Home",
            services: "Services",
            about: "About",
            contact: "Contact",
            clientSpace: "Client Area",
            login: "Login",
            logout: "Logout",
            security: "Security & Password",
            subtitle: "Yado_Bank",
            theme: "Theme",
            dashboard: "Dashboard",
            menu: "Menu"
        },
        sidebar: {
            admin: "Administration",
            dashboard: "Dashboard",
            agentSpace: "Agent Area",
            managementConsole: "Management Console",
            newClient: "New Client",
            myAccount: "My Account",
            myDashboard: "My Dashboard",
            makeTransfer: "Make a Transfer",
            becomeClient: "Become a Client",
            howItWorks: "How it works",
            faq: "FAQ",
            contactUs: "Contact Us",
            needHelp: "Need help?",
            advisors: "Our advisors are here for you."
        },
        home: {
            heroTitle: "Your bank,",
            heroTitleAccent: "your future.",
            heroDesc: "Innovative and secure banking solutions to support all your life projects. Banking excellence at the service of your success.",
            accessAccount: "Access my account",
            discoverOffers: "Discover our offers",
            servicesTitle: "Excellence Services",
            s1Title: "Maximum Security",
            s1Desc: "Your data and transactions are protected by the most advanced encryption protocols.",
            s2Title: "Online Banking 24/7",
            s2Desc: "Access your accounts, make transfers and manage your savings wherever you are.",
            s3Title: "Premium Cards",
            s3Desc: "Bank cards adapted to your lifestyle with exclusive limits and insurance.",
            readyTitle: "Ready to join us?",
            readyDesc: "Open an account in minutes and enjoy banking services reimagined for you.",
            contactAdvisor: "Contact an Advisor"
        },
        services: {
            title: "A complete range of services",
            subtitle: "OUR SOLUTIONS",
            intro: "Discover our banking solutions designed to meet all your daily needs and future projects.",
            cards: {
                secure: { title: "Secure Accounts", desc: "Current and savings accounts with military-grade security." },
                intl: { title: "International Transfers", desc: "Send money anywhere in the world with competitive rates." },
                cards: { title: "Premium Cards", desc: "A wide range of bank cards (Gold, Platinum, Infinite)." },
                wealth: { title: "Wealth Management", desc: "Dedicated experts to optimize your investments." },
                mobile: { title: "Mobile Banking", desc: "Manage your accounts at your fingertips with our app." },
                support: { title: "Dedicated Support", desc: "A team of experts at your disposal 7/7." }
            }
        },
        about: {
            title: "Excellence since 2026",
            subtitle: "OUR HISTORY",
            whoTitle: "Who are we?",
            whoDesc1: "Yado_Bank was born from the vision of two experts, Yasser Habri and Doha Allali, wishing to redefine the banking experience in Morocco.",
            whoDesc2: "Our mission is simple: to offer each client tailor-made support.",
            excellenceTitle: "Excellence & Innovation",
            excellenceDesc: "We purely invest in the latest technologies.",
            proximityTitle: "Client Proximity",
            proximityDesc: "More than a bank, we are a trusted partner."
        },
        contact: {
            title: "Contact Us",
            subtitle: "A QUESTION?",
            coordsTitle: "Our Contact Info",
            formTitle: "Send us a message",
            name: "Last Name",
            firstname: "First Name",
            message: "Message",
            placeholderMsg: "How can we help you?",
            btnSend: "Send Message"
        },
        login: {
            title: "Client Area",
            agentTitle: "Staff Access",
            subtitle: "Log in to your online bank",
            agentSubtitle: "Restricted access for Yado_Bank staff",
            usernamePlaceholder: "Username",
            agentPlaceholder: "Staff ID",
            passwordPlaceholder: "••••••••••••",
            forgotPassword: "Forgot password?",
            loginBtn: "Log in",
            footer: "© 2026 Yasser Habri & Doha Allali Bank. All rights reserved.",
            tabClient: "Client",
            tabAgent: "Staff"
        },
        admin: {
            title: "Control Center",
            subtitle: "Global management and supervision of banking architecture.",
            badge: "Super Admin",
            activeAgents: "Active Agents",
            volume: "Global Volume",
            health: "System Health",
            staffList: "Staff",
            addAgent: "Add Agent",
            noAgents: "No agents found."
        },
        agent: {
            title: "Management Console",
            subtitle: "Centralized administration of clients and bank accounts.",
            badge: "Agent Area",
            newClient: "New Client",
            newAccount: "New Account",
            clientsTab: "Clients",
            accountsTab: "Accounts",
            searchClient: "Search client (Name, ID)...",
            searchAccount: "Search account (IBAN)...",
            noClients: "No clients found.",
            noAccounts: "No accounts found.",
            balance: "Balance",
            type: "Type"
        },
        client: {
            title: "My Accounts",
            subtitle: "Overview of your assets.",
            badge: "Client Area",
            newTransfer: "New Transfer",
            balance: "Current Balance",
            history: "Transaction History",
            noOps: "No transactions found.",
            credit: "CREDIT",
            debit: "DEBIT"
        }
    },
    es: {
        common: {
            loading: "Cargando...",
            send: "Enviar",
            sending: "Enviando...",
            sent: "¡Enviado!",
            back: "Volver",
            error: "Error",
            email: "Correo",
            password: "Contraseña",
            submit: "Validar",
            cancel: "Cancelar",
            save: "Guardar",
            delete: "Eliminar",
            edit: "Editar",
            search: "Buscar...",
            actions: "Acciones",
            status: "Estado",
            active: "Activo",
            blocked: "Bloqueado",
            suspended: "Suspendido",
            id: "ID",
            date: "Fecha",
            amount: "Monto",
            description: "Descripción",
            type: "Tipo"
        },
        navbar: {
            home: "Inicio",
            services: "Servicios",
            about: "Sobre nosotros",
            contact: "Contacto",
            clientSpace: "Área Cliente",
            login: "Conexión",
            logout: "Desconectar",
            security: "Seguridad y Contraseña",
            subtitle: "Yado_Bank",
            theme: "Tema",
            dashboard: "Tablero",
            menu: "Menú"
        },
        sidebar: {
            admin: "Administración",
            dashboard: "Tablero",
            agentSpace: "Área de Agente",
            managementConsole: "Consola de Gestión",
            newClient: "Nuevo Cliente",
            myAccount: "Mi Cuenta",
            myDashboard: "Mi Tablero",
            makeTransfer: "Hacer una transferencia",
            becomeClient: "Hacerse cliente",
            howItWorks: "Cómo funciona",
            faq: "Preguntas frecuentes",
            contactUs: "Contáctenos",
            needHelp: "¿Necesita ayuda?",
            advisors: "Nuestros asesores están aquí para usted."
        },
        home: {
            heroTitle: "Tu banco,",
            heroTitleAccent: "tu futuro.",
            heroDesc: "Soluciones bancarias innovadoras y seguras para acompañar todos tus proyectos de vida. Excelencia bancaria al servicio de tu éxito.",
            accessAccount: "Acceder a mi cuenta",
            discoverOffers: "Descubrir ofertas",
            servicesTitle: "Servicios de Excelencia",
            s1Title: "Seguridad Máxima",
            s1Desc: "Tus datos y transacciones están protegidos por los protocolos de encriptación más avanzados.",
            s2Title: "Banca en Línea 24/7",
            s2Desc: "Accede a tus cuentas, realiza transferencias y gestiona tus ahorros donde quiera que estés.",
            s3Title: "Tarjetas Premium",
            s3Desc: "Tarjetas bancarias adaptadas a tu estilo de vida con límites y seguros exclusivos.",
            readyTitle: "¿Listo para unirte?",
            readyDesc: "Abre una cuenta en minutos y disfruta de servicios bancarios reinventados para ti.",
            contactAdvisor: "Contactar un asesor"
        },
        services: {
            title: "Una gama completa de servicios",
            subtitle: "NUESTRAS SOLUCIONES",
            intro: "Descubre nuestras soluciones bancarias diseñadas para satisfacer todas tus necesidades diarias.",
            cards: {
                secure: { title: "Cuentas Seguras", desc: "Cuentas corrientes y de ahorro con seguridad de nivel militar." },
                intl: { title: "Transferencias Internacionales", desc: "Envía dinero a cualquier parte del mundo con tarifas competitivas." },
                cards: { title: "Tarjetas Premium", desc: "Una amplia gama de tarjetas (Gold, Platinum, Infinite)." },
                wealth: { title: "Gestión de Patrimonio", desc: "Expertos dedicados para optimizar tus inversiones." },
                mobile: { title: "Banca Móvil", desc: "Gestiona tus cuentas al alcance de tu mano." },
                support: { title: "Servicio al Cliente", desc: "Un equipo de expertos a tu disposición 7/7." }
            }
        },
        about: {
            title: "Excelencia desde 2026",
            subtitle: "NUESTRA HISTORIA",
            whoTitle: "¿Quiénes somos?",
            whoDesc1: "Yado_Bank nació de la visión de dos expertos, Yasser Habri y Doha Allali, deseando redefinir la experiencia bancaria en Marruecos.",
            whoDesc2: "Nuestra misión es simple: ofrecer a cada cliente un acompañamiento a medida.",
            excellenceTitle: "Excelencia e Innovación",
            excellenceDesc: "Invertimos continuamente en las últimas tecnologías.",
            proximityTitle: "Proximidad al Cliente",
            proximityDesc: "Más que un banco, somos un socio de confianza."
        },
        contact: {
            title: "Contáctanos",
            subtitle: "¿UNA PREGUNTA?",
            coordsTitle: "Nuestros Datos",
            formTitle: "Envíanos un mensaje",
            name: "Apellido",
            firstname: "Nombre",
            message: "Mensaje",
            placeholderMsg: "¿Cómo podemos ayudarte?",
            btnSend: "Enviar mensaje"
        },
        login: {
            title: "Área Cliente",
            agentTitle: "Acceso Personal",
            subtitle: "Conéctate a tu banca en línea",
            agentSubtitle: "Acceso restringido al personal",
            usernamePlaceholder: "Nombre de usuario",
            agentPlaceholder: "ID de empleado",
            passwordPlaceholder: "••••••••••••",
            forgotPassword: "¿Olvidaste tu contraseña?",
            loginBtn: "Conectarse",
            footer: "© 2026 Yasser Habri & Doha Allali Bank. Todos los derechos reservados.",
            tabClient: "Cliente",
            tabAgent: "Personal"
        },
        admin: {
            title: "Centro de Control",
            subtitle: "Gestión global y supervisión de la arquitectura bancaria.",
            badge: "Super Admin",
            activeAgents: "Agentes Activos",
            volume: "Volumen Global",
            health: "Salud del Sistema",
            staffList: "Personal",
            addAgent: "Añadir Agente",
            noAgents: "No se encontraron agentes."
        },
        agent: {
            title: "Consola de Gestión",
            subtitle: "Administración centralizada de clientes y cuentas bancarias.",
            badge: "Área de Agente",
            newClient: "Nuevo Cliente",
            newAccount: "Nueva Cuenta",
            clientsTab: "Clientes",
            accountsTab: "Cuentas",
            searchClient: "Buscar cliente (Nombre, ID)...",
            searchAccount: "Buscar cuenta (IBAN)...",
            noClients: "No se encontraron clientes.",
            noAccounts: "No se encontraron cuentas.",
            balance: "Saldo",
            type: "Tipo"
        },
        client: {
            title: "Mis Cuentas",
            subtitle: "Resumen de su patrimonio.",
            badge: "Área Cliente",
            newTransfer: "Nueva Transferencia",
            balance: "Saldo Actual",
            history: "Historial de Operaciones",
            noOps: "No se encontraron operaciones.",
            credit: "CRÉDITO",
            debit: "DÉBITO"
        }
    },
    ar: {
        common: {
            loading: "جار التحميل...",
            send: "إرسال",
            sending: "جار الإرسال...",
            sent: "تم الإرسال!",
            back: "رجوع",
            error: "خطأ",
            email: "البريد الإلكتروني",
            password: "كلمة المرور",
            submit: "تأكيد",
            cancel: "إلغاء",
            save: "حفظ",
            delete: "حذف",
            edit: "تعديل",
            search: "بحث...",
            actions: "إجراءات",
            status: "الحالة",
            active: "نشط",
            blocked: "محظور",
            suspended: "معلق",
            id: "رقم",
            date: "التاريخ",
            amount: "المبلغ",
            description: "الوصف",
            type: "النوع"
        },
        navbar: {
            home: "الرئيسية",
            services: "خدماتنا",
            about: "من نحن",
            contact: "اتصل بنا",
            clientSpace: "فضاء الزبناء",
            login: "تسجيل الدخول",
            logout: "خروج",
            security: "الأمان وكلمة المرور",
            subtitle: "يادو_بنك",
            theme: "المظهر",
            dashboard: "لوحة التحكم",
            menu: "القائمة"
        },
        sidebar: {
            admin: "الإدارة",
            dashboard: "لوحة التحكم",
            agentSpace: "فضاء الوكيل",
            managementConsole: "وحدة التحكم",
            newClient: "زبون جديد",
            myAccount: "حسابي",
            myDashboard: "لوحة تحكمي",
            makeTransfer: "إجراء تحويل",
            becomeClient: "كن زبوناً",
            howItWorks: "كيف يعمل",
            faq: "أسئلة شائعة",
            contactUs: "اتصل بنا",
            needHelp: "تحتاج مساعدة؟",
            advisors: "مستشارونا هنا من أجلك."
        },
        home: {
            heroTitle: "بنكك،",
            heroTitleAccent: "مستقبلك.",
            heroDesc: "حلول بنكية مبتكرة وآمنة لمرافقة جميع مشاريع حياتك. التميز البنكي في خدمة نجاحك.",
            accessAccount: "الدخول إلى حسابي",
            discoverOffers: "اكتشف عروضنا",
            servicesTitle: "خدمات متميزة",
            s1Title: "أمان قصوى",
            s1Desc: "بياناتك ومعاملاتك محمية بأحدث بروتوكولات التشفير.",
            s2Title: "بنك إلكتروني 24/7",
            s2Desc: "ادخل إلى حساباتك، قم بتحويلاتك ودبر مدخراتك أينما كنت.",
            s3Title: "بطاقات متميزة",
            s3Desc: "بطاقات بنكية تناسب نمط حياتك مع سقوف وتأمين حصري.",
            readyTitle: "مستعد للانضمام إلينا؟",
            readyDesc: "افتح حساباً في دقائق واستمتع بخدمات بنكية أعيد ابتكارها من أجلك.",
            contactAdvisor: "تحدث مع مستشار"
        },
        services: {
            title: "مجموعة خدمات شاملة",
            subtitle: "حلولنا",
            intro: "اكتشف حلولنا البنكية المصممة لتلبية جميع احتياجاتك اليومية ومشاريعك المستقبلية.",
            cards: {
                secure: { title: "حسابات آمنة", desc: "حسابات جارية وتوفير بأمان عالٍ." },
                intl: { title: "تحويلات دولية", desc: "أرسل الأموال إلى أي مكان في العالم بأسعار تنافسية." },
                cards: { title: "بطاقات متميزة", desc: "مجموعة واسعة من البطاقات (ذهبية، بلاتينية، إنفينيت)." },
                wealth: { title: "إدارة الثروات", desc: "خبراء مخصصون لتحسين استثماراتك." },
                mobile: { title: "بنك المحمول", desc: "دبر حساباتك بلمسة زر عبر تطبيقنا." },
                support: { title: "خدمة زبناء مخصصة", desc: "فريق من الخبراء رهن إشارتك 7/7." }
            }
        },
        about: {
            title: "التميز منذ 2026",
            subtitle: "تاريخنا",
            whoTitle: "من نحن؟",
            whoDesc1: "ولد يادو_بنك من رؤية خبيرين، ياسر هبري وضحى علالي، ورغبتهما في إعادة تعريف التجربة البنكية في المغرب.",
            whoDesc2: "مهمتنا بسيطة: تقديم مرافقة مخصصة لكل زبون.",
            excellenceTitle: "التميز والابتكار",
            excellenceDesc: "نستثمر باستمرار في أحدث التقنيات.",
            proximityTitle: "القرب من الزبون",
            proximityDesc: "أكثر من مجرد بنك، نحن شريك موثوق."
        },
        contact: {
            title: "اتصل بنا",
            subtitle: "لديك سؤال؟",
            coordsTitle: "معلوماتنا",
            formTitle: "أرسل لنا رسالة",
            name: "اللقب",
            firstname: "الاسم",
            message: "الرسالة",
            placeholderMsg: "كيف يمكننا مساعدتك؟",
            btnSend: "إرسال الرسالة"
        },
        login: {
            title: "فضاء الزبناء",
            agentTitle: "فضاء الموظفين",
            subtitle: "تصل ببنكك الإلكتروني",
            agentSubtitle: "دخول مخصص لموظفي البنك",
            usernamePlaceholder: "اسم المستخدم",
            agentPlaceholder: "رقم الموظف",
            passwordPlaceholder: "••••••••••••",
            forgotPassword: "نسيت كلمة المرور؟",
            loginBtn: "تواصل",
            footer: "© 2026 بنك ياسر هبري وضحى علالي. جميع الحقوق محفوظة.",
            tabClient: "زبون",
            tabAgent: "موظف"
        },
        admin: {
            title: "مركز التحكم",
            subtitle: "الإدارة العامة والإشراف على البنية التحتية البنكية.",
            badge: "مدير عام",
            activeAgents: "الوكلاء النشطون",
            volume: "الحجم الإجمالي",
            health: "صحة النظام",
            staffList: "الموظفون",
            addAgent: "إضافة وكيل",
            noAgents: "لم يتم العثور على وكلاء."
        },
        agent: {
            title: "وحدة التحكم",
            subtitle: "الإدارة المركزية للزبناء والحسابات البنكية.",
            badge: "فضاء الوكيل",
            newClient: "زبون جديد",
            newAccount: "حساب جديد",
            clientsTab: "الزبناء",
            accountsTab: "الحسابات",
            searchClient: "بحث عن زبون (الاسم، ر.ب.و)...",
            searchAccount: "بحث عن حساب (ريب)...",
            noClients: "لم يتم العثور على زبناء.",
            noAccounts: "لم يتم العثور على حسابات.",
            balance: "الرصيد",
            type: "النوع"
        },
        client: {
            title: "حساباتي",
            subtitle: "نظرة عامة على ممتلكاتك.",
            badge: "فضاء الزبون",
            newTransfer: "تحويل جديد",
            balance: "الرصيد الحالي",
            history: "تاريخ العمليات",
            noOps: "لم يتم العثور على أي عملية.",
            credit: "دائن",
            debit: "مدين"
        }
    }
};
